# Build and deploy the app

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1.4.2
      with:
        node-version: '10.x'
 
    - name: Build
      run: |
        npm install
        npm run build
    - name: Deploy
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@3.4.8
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/lottery
